### ISSUE TITLE
using static error

### ISSUE THREAD

**Issue by izzycollo** [PPrism/TerrariaOGC#2]
i used to have terraria on my ps3 me and my brother used to play all the time so i wanted to relive these memories and i found this. i have the real version of terraria on steam and i was like yeah i can download it and  i followed all the instructions 9 times and everytime i did it says when i try to build it static error upgrade to c#6 and if i do that then the code would be wrong and theres an error message that says Metadata file 'C:\Users\\Desktop\TerrariaOGC\FNA\bin\x64\Release\net4.0\FNA.dll' could not be found i would really appreciate it if i could get any help with this. or i can get a prebuilt version because i did this 9! times

**Comment by PPrism** [comment]
Hi, 
I just redid the setup myself and encountered that same error; not sure why it appeared there but I found that upgrading the project works just fine.

You can go ahead and use VS' suggestion of upgrading the project as that will allow you to then use 'Build solution' in the 'Build' tab without any issues (At least it did for me).

**Comment by izzycollo** [comment]
so apparently that did not work really well... some item ids have errors idk if im missing somthing

**Comment by izzycollo** [comment]
tryed it 3 times and still the same error

**Comment by PPrism** [comment]
Could be that the version isn't being defined properly for some reason. I'll add you and then after we sort it out, I'll report the fix here in the event it is a larger issue.

**Comment by MunchBunch3rd** [comment]
So what was the solution?

**Comment by 12TKD21** [comment]
I'm running into the same issue if you have a solution please let us know

**Comment by PPrism** [comment]
If I recall, the issue is that a 1.2 version is attempting to be built, which cannot occur since it’s not implemented. Has to be only 1.1.2 or one of the initial versions.

**Comment by 12TKD21** [comment]
I tried building every available version but I get the same error mentioned above. Whenever you have the time a fix would be helpful. I'd love to check this out.

**Comment by PPrism** [comment]
Problem is that I don’t get it, so it would be related to your VS setup. Have you tried any quick fixes suggested by VS? Sounds like the compiler needs to be updated.
